export const ACTION_TYPE = {
	SET_SESSION: 'SET_SESSION',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	FETCH_PROJECTS_REQUEST: 'FETCH_PROJECTS_REQUEST',
	RESET_PROJECT_DATA: 'RESET_PROJECT_DATA',
	SET_PROJECT_LOADING: 'SET_PROJECT_LOADING',
	SET_PROJECTS_DATA: 'SET_PROJECTS_DATA',
	SET_PROJECT_ERROR: 'SET_PROJECT_ERROR',
	SET_PROJECT_PAGE: 'SET_PROJECT_PAGE',
	CREATE_PROJECT: 'CREATE_PROJECT',
};
